const express = require("express");
const router = express.Router();

const elements = [
    { symbol: "H", group: "Otros_no_metales", position: "_1"},
    { symbol: "HE", group: "Gases", position: "_2"},
  
    { symbol: "Li", group: "Alcalinos", position: "_3"},
    { symbol: "Be", group: "Alcalinoterreos", position: "_4"},
    { symbol: "B", group: "Metaloides", position: "_5"},
    { symbol: "C", group: "Otros_no_metales", position: "_6"},
    { symbol: "N", group: "Otros_no_metales", position: "_7"},
    { symbol: "O", group: "Otros_no_metales", position: "_8"},
    { symbol: "F", group: "Halogenos", position: "_9"},
    { symbol: "Ne", group: "Gases", position: "_10"},
  
    { symbol: "Na", group: "Alcalinos", position: "_11"},
    { symbol: "Mg", group: "Alcalinoterreos", position: "_12"},
    { symbol: "Al", group: "Otros_metales", position: "_13"},
    { symbol: "Si", group: "Metaloides", position: "_14"},
    { symbol: "P", group: "Otros_no_metales", position: "_15"},
    { symbol: "S", group: "Otros_no_metales", position: "_16"},
    { symbol: "Cl", group: "Halogenos", position: "_17"},
    { symbol: "Ar", group: "Gases", position: "_18"},
  
    { symbol: "K", group: "Alcalinos", position: "_19"},
    { symbol: "Ca", group: "Alcalinoterreos", position: "_20"},
    { symbol: "Sc", group: "Metales", position: "_21"},
    { symbol: "Ti", group: "Metales", position: "_22"},
    { symbol: "V", group: "Metales", position: "_23"},
    { symbol: "Cr", group: "Metales", position: "_24"},
    { symbol: "Mn", group: "Metales", position: "_25"},
    { symbol: "Fe", group: "Metales", position: "_26"},
    { symbol: "Co", group: "Metales", position: "_27"},
    { symbol: "Ni", group: "Metales", position: "_28"},
    { symbol: "Cu", group: "Metales", position: "_29"},
    { symbol: "Zn", group: "Metales", position: "_30"},
    { symbol: "Ga", group: "Otros_metales", position: "_31"},
    { symbol: "Ge", group: "Metaloides", position: "_32"},
    { symbol: "As", group: "Metaloides", position: "_33"},
    { symbol: "Se", group: "Otros_no_metales", position: "_34"},
    { symbol: "Br", group: "Halogenos", position: "_35"},
    { symbol: "Kr", group: "Gases", position: "_36"},
  
    { symbol: "Rb", group: "Alcalinos", position: "_37"},
    { symbol: "Sr", group: "Alcalinoterreos", position: "_38"},
    { symbol: "Y", group: "Metales", position: "_39"},
    { symbol: "Zr", group: "Metales", position: "_40"},
    { symbol: "Nb", group: "Metales", position: "_41"},
    { symbol: "Mo", group: "Metales", position: "_42"},
    { symbol: "Tc", group: "Metales", position: "_43"},
    { symbol: "Ru", group: "Metales", position: "_44"},
    { symbol: "Rh", group: "Metales", position: "_45"},
    { symbol: "Pd", group: "Metales", position: "_46"},
    { symbol: "Ag", group: "Metales", position: "_47"},
    { symbol: "Cd", group: "Metales", position: "_48"},
    { symbol: "ln", group: "Otros_metales", position: "_49"},
    { symbol: "Sn", group: "Otros_metales", position: "_50"},
    { symbol: "Sb", group: "Metaloides", position: "_51"},
    { symbol: "Te", group: "Metaloides", position: "_52"},
    { symbol: "l", group: "Halogenos", position: "_53"},
    { symbol: "Xe", group: "Gases", position: "_54"},
  
    { symbol: "Cs", group: "Alcalinos", position: "_55"},
    { symbol: "Ba", group: "Alcalinoterreos", position: "_56"},
    { symbol: "La-Lu", group: "Lantanidos", position: "_57"},
    { symbol: "Hf", group: "Metales", position: "_58"},
    { symbol: "Ta", group: "Metales", position: "_59"},
    { symbol: "W", group: "Metales", position: "_60"},
    { symbol: "Re", group: "Metales", position: "_61"},
    { symbol: "Os", group: "Metales", position: "_62"},
    { symbol: "Ir", group: "Metales", position: "_63"},
    { symbol: "Pt", group: "Metales", position: "_64"},
    { symbol: "Au", group: "Metales", position: "_65"},
    { symbol: "Hg", group: "Metales", position: "_66"},
    { symbol: "Tl", group: "Otros_metales", position: "_67"},
    { symbol: "Pb", group: "Otros_metales", position: "_68"},
    { symbol: "Bi", group: "Otros_metales", position: "_69"},
    { symbol: "Po", group: "Metaloides", position: "_70"},
    { symbol: "At", group: "Halogenos", position: "_71"},
    { symbol: "Rn", group: "Gases", position: "_72"},
    
    { symbol: "Fr", group: "Alcalinos", position: "_73"},
    { symbol: "Ra", group: "Alcalinoterreos", position: "_74"},
    { symbol: "Ac-Lr", group: "Actinidos", position: "_75"},
    { symbol: "Rf", group: "Metales", position: "_76"},
    { symbol: "Db", group: "Metales", position: "_77"},
    { symbol: "Sg", group: "Metales", position: "_78"},
    { symbol: "Bh", group: "Metales", position: "_79"},
    { symbol: "Hs", group: "Metales", position: "_80"},
    { symbol: "Mt", group: "Metales", position: "_81"},
    { symbol: "Ds", group: "Metales", position: "_82"},
    { symbol: "Rg", group: "Metales", position: "_83"},
    { symbol: "Cn", group: "Metales", position: "_84"},
    { symbol: "Nh", group: "Otros_metales", position: "_85"},
    { symbol: "Fl", group: "Otros_metales", position: "_86"},
    { symbol: "Mc", group: "Otros_metales", position: "_87"},
    { symbol: "Lv", group: "Otros_metales", position: "_88"},
    { symbol: "Ts", group: "Halogenos", position: "_89"},
    { symbol: "Og", group: "Gases", position: "_90"},
  
    { symbol: "La", group: "Lantanidos", position: "_91"},
    { symbol: "Ce", group: "Lantanidos", position: "_92"},
    { symbol: "Pr", group: "Lantanidos", position: "_93"},
    { symbol: "Nd", group: "Lantanidos", position: "_94"},
    { symbol: "Pm", group: "Lantanidos", position: "_95"},
    { symbol: "Sm", group: "Lantanidos", position: "_96"},
    { symbol: "Eu", group: "Lantanidos", position: "_97"},
    { symbol: "Gd", group: "Lantanidos", position: "_98"},
    { symbol: "Tb", group: "Lantanidos", position: "_99"},
    { symbol: "Dy", group: "Lantanidos", position: "_100"},
    { symbol: "Ho", group: "Lantanidos", position: "_101"},
    { symbol: "Er", group: "Lantanidos", position: "_102"},
    { symbol: "Tm", group: "Lantanidos", position: "_103"},
    { symbol: "Yb", group: "Lantanidos", position: "_104"},
    { symbol: "Lu", group: "Lantanidos", position: "_105"},
  
    { symbol: "Ac", group: "Actinidos", position: "_106"},
    { symbol: "Th", group: "Actinidos", position: "_107"},
    { symbol: "Pa", group: "Actinidos", position: "_108"},
    { symbol: "U", group: "Actinidos", position: "_109"},
    { symbol: "Np", group: "Actinidos", position: "_110"},
    { symbol: "Pu", group: "Actinidos", position: "_111"},
    { symbol: "Am", group: "Actinidos", position: "_112"},
    { symbol: "Cm", group: "Actinidos", position: "_113"},
    { symbol: "Bk", group: "Actinidos", position: "_114"},
    { symbol: "Cf", group: "Actinidos", position: "_115"},
    { symbol: "Es", group: "Actinidos", position: "_116"},
    { symbol: "Fm", group: "Actinidos", position: "_117"},
    { symbol: "Md", group: "Actinidos", position: "_118"},
    { symbol: "No", group: "Actinidos", position: "_119"},
    { symbol: "Lr", group: "Actinidos", position: "_120"},
  ];

router.get("/", function (req, res, next) {
  res.render("home", { layout: false, elements: elements });
});

module.exports = router;